### ISSUE TITLE
Remove onclick action on one of the TD in collapsible row

### ISSUE THREAD

**Issue by ghost** [DmitriiSer/angular2-collapsible-example#2]
Hi, 

I have implemented your angular2-collapsible, and it works very good. So, thank you, for a neat module that you built.

I have one request from this module. I have a row that expands with further details in them. Now, there is a drop down column in this row (that is expandable on click). whenever I click this drop-down, to select some option, the whole row gets clicked and the whole row expands instead of just this column's drop-down expand. 

How do I remove this expand property from this just one column, that has drop-down code(select drop-down).

Any pointers greatly appreciated.

Thank you,
Omnisri

**Comment by DmitriiSer** [comment]
You can find a fix in the latest version. **[angular2-collapsible](https://github.com/DmitriiSer/angular2-collapsible)** won't trigger row expansion if you click on anything else besides **TR** / **TD** elements.

Please let me know if that fixed your issue.

**Comment by ghost** [comment]
Thank you @DmitriiSer , for the reply and fix. Am gonna test it tonight and let you know if that helped my requirement. Again, thank you, for the fix.

**Comment by ghost** [comment]
So, I tried updating the version of angular2-collapsible and still somehow unable to expand my select dropdown as intented. All I want is is to open my drop down like any other dropdown and select an option from there. Currently when I click on the drop down, it only stays open for like blink of a second and immediately closes. Am I doing something wrong?

```
<div class="sampleclass">
<h5 style="color: #008080;font-weight:bold">Table Data!</h5>
<collapsible-table [type]="'accordion'" bordered="true" striped="true">
          <thead>
            <collapsible-table-row>
              <th>Test Name</th>
              <th>Test MTest </th>
              <th>Test </th>
              <th>Test </th>
              <th>Test </th>
            </collapsible-table-row>
          </thead>
      
          <tbody *ngFor="let tad of datatable">
            <collapsible-table-row [detail]="detail">
              <td>{{tad .test}}</td>
              <td>{{tad .firstName}}</td>
              <td>{{tad .testarea}}</td>
              <td>{{tad .testplay}}</td>
              <td>
                <div>
                  <select>
                    <option value="">please select an option</option>
                    <option *ngFor="let kat of Types">{{kat.dropdownoption}}</option>
                  </select>
                </div>
              </td>
            </collapsible-table-row>
            <collapsible-table-row-detail #detail centered="true">
              <div class="container" style="margin-bottom:25px;margin-left: 10%;width: 40%;">
                <p style="font-weight:bold;margin-top:25px;">Details: {{tad.name}}</p>
                <hr style="margin-top:0px;margin-bottom:0px;">
                <div class="right">
                  {{tad.test}} <br>
                 ////// expanded view
                </div>
              </div>
            </collapsible-table-row-detail>
          </tbody>
        </collapsible-table>
      </div>
```

Could you please let me know if am may be doing something different here? I am on a verge of re-writing the page, which I really don't wanna do :) I really like the functionality of this module. So, kindly, help me out here.

**Comment by ghost** [comment]
hi @DmitriiSer , I was able to test this and it works as expected!! YAYYYY!! I cannot be more happier :+1: 
I had to restart my app several times for changes to reflect, but it worked eventually. Apparently it was my local machine thing!

Thank you, once again for the fix.
